name: app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../assets/icon.png"
  remove_alpha_ios: true
