name: Test and release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Get dependencies
      run: flutter pub get

    - name: Static code checks
      run: flutter analyze --fatal-warnings

    - name: Run tests
      run: flutter test --dart-define=THE_CAT_API_KEY=${{ secrets.THE_CAT_API_KEY }}

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release-key.jks

    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=app/release-key.jks" >> android/key.properties

    - name: Build APK
      run: flutter build apk --release --dart-define=THE_CAT_API_KEY=${{ secrets.THE_CAT_API_KEY }}

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
